[package]
name = "telemetry"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json.workspace = true
chrono = { version = "0.4", default-features = false, features = ["std"] }
http-body-util = "0.1"
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
tokio.workspace = true
