services:
  speaker1:
    image: roggnetwork/bgpgg:latest
    container_name: rogg1
    configs:
      - source: speaker1_config
        target: /etc/rogg/rogg.conf
    networks:
      bgp_network:
        ipv4_address: 172.20.0.10

  speaker2:
    image: roggnetwork/bgpgg:latest
    container_name: rogg2
    configs:
      - source: speaker2_config
        target: /etc/rogg/rogg.conf
    networks:
      bgp_network:
        ipv4_address: 172.20.0.20

configs:
  speaker1_config:
    content: |
      service bgp {
        asn 65001
        router-id 1.1.1.1
        listen-addr 0.0.0.0:179

        peer 172.20.0.20 {
          remote-as 65002
        }
      }

  speaker2_config:
    content: |
      service bgp {
        asn 65002
        router-id 2.2.2.2
        listen-addr 0.0.0.0:179

        peer 172.20.0.10 {
          remote-as 65001
        }
      }

networks:
  bgp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
