[package]
name = "bgpgg"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bgpggd"
path = "src/bin/bgpggd.rs"

[dependencies]
tokio.workspace = true
tokio-stream = "0.1"
tonic.workspace = true
prost.workspace = true
clap.workspace = true
serde.workspace = true
serde_yaml.workspace = true
serde_json.workspace = true
regex.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
libc = "0.2"
conf = { path = "../conf" }
telemetry = { path = "../telemetry" }
russh = "0.58"
uuid.workspace = true

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
tonic-build = "0.12"
